apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: storage
  namespace: default
spec:
  chart:
    spec:
      chart: storage
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    host:
      enabled: false
    nfs:
      server:
        address: "172.26.59.13"
    domain:
      resman:
        storageClass: eoepca-nfs
      proc:
        enabled: true
        storageClass: eoepca-nfs
      userman:
        storageClass: eoepca-nfs
  interval: 1m0s
