---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: django-portal
  namespace: demo
spec:
  chart:
    spec:
      chart: django-portal
      version: 1.0.7
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    domain: 89.202.251.199.nip.io
    authHost: auth
    configmap:
      user_prefix: develop-user
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
  interval: 1m0s
