apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: workspace-api
  namespace: rm
spec:
  interval: 5m
  chart:
    spec:
      chart: rm-workspace-api
      version: 1.1.11
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    fullnameOverride: workspace-api
    image: # {}
      # repository: eoepca/rm-workspace-api
      # pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "1.2-dev2"

    ingress:
      enabled: true
      hosts:
        - host: workspace-api-open.172.26.59.10.nip.io
          paths: ["/"]
      tls:
        - hosts:
            - workspace-api-open.172.26.59.10.nip.io
          secretName: workspace-api-tls

    # some values for the workspace API
    prefixForName: "develop-user"
    workspaceSecretName: "bucket"
    namespaceForBucketResource: "rm"
    s3Endpoint: "https://cf2.cloudferro.com:8080"
    s3Region: "RegionOne"
    harborUrl: "https://harbor.172.26.59.10.nip.io"
    harborUsername: "admin"
    harborPassword: "eoepcaHarborx83NX3tVpSLAgg9UuusQ"
    umaClientSecretName: "rm-uma-user-agent"
    umaClientSecretNamespace: "rm"
    workspaceChartsConfigMap: "workspace-charts"
