apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: um-login-service
  namespace: um
spec:
  chart:
    spec:
      chart: login-service
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    volumeClaim:
      name: eoepca-userman-pvc
      create: false
    config:
      domain: auth.89.202.251.199.nip.io
      volumeClaim:
        name: eoepca-userman-pvc
    opendj:
      # This can be useful to workaround helm 'failed to upgrade' errors due to
      # immutable fields in the 'um-login-service-persistence-init-ss' job
      # persistence:
      #   enabled: false
      volumeClaim:
        name: eoepca-userman-pvc
    oxauth:
      volumeClaim:
        name: eoepca-userman-pvc
    oxtrust:
      volumeClaim:
        name: eoepca-userman-pvc
    global:
      domain: auth.89.202.251.199.nip.io
      nginxIp: 89.202.251.199
      namespace: um
    nginx:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - auth.89.202.251.199.nip.io
        tls:
          - hosts:
              - auth.89.202.251.199.nip.io
            secretName: login-service-tls
  timeout: 25m0s
  interval: 1m0s
